import type { Metadata } from "next";
import { AudioProvider } from "./components/AudioProvider";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import StarknetProvider from "./components/starknet-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// const { isPlaying, volume, togglePlay, setVolume } = useAudio()

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <StarknetProvider>
          <AudioProvider>{children}</AudioProvider>
        </StarknetProvider>
      </body>
    </html>
  );
}
